language: c
sudo: required

env:
  global:
     - APPLICATION_FOLDER="${HOME}/arduino-ide"
     - SKETCHBOOK_FOLDER="${HOME}/arduino-sketchbook"
     - EXAMPLES_DIR="${SKETCHBOOK_FOLDER}/libraries/WiFiManager/examples"
     - ESP8266_DEVICE="esp8266:esp8266:generic:CpuFrequency=80,CrystalFreq=26,FlashFreq=40,FlashMode=qio,FlashSize=4M1M,led=2,LwIPVariant=v2mss536,Debug=Serial,DebugLevel=CORE"
     - ESP32_DEVICE="espressif:esp32:esp32doit-devkit-v1:FlashFreq=80,DebugLevel=info"

before_install:
  # setup arduino-ci-script
  - git clone https://github.com/per1234/arduino-ci-script.git "${HOME}/scripts"
  - cd "${HOME}/scripts"
  # Get new tags from the remote
  - git fetch --tags
  # Checkout the latest tag
  - git checkout $(git describe --tags `git rev-list --tags --max-count=1`)
  - source "${HOME}/scripts/arduino-ci-script.sh"

  # Uncomment the following lines to get verbose output for debugging
  # 0 (minimum/default) - 2 (maximum) verbosity
  #- set_script_verbosity 1
  # Turn on verbose output during compilation
  #- set_verbose_output_during_compilation "true"

  # Check for library issues that don't affect compilation
  - set_library_testing "true"

  - set_application_folder "$APPLICATION_FOLDER"
  - set_sketchbook_folder "$SKETCHBOOK_FOLDER"

  - install_ide "1.8.5"

  - install_package "esp8266:esp8266" "http://arduino.esp8266.com/stable/package_esp8266com_index.json"

  # install esp32 arduino code manually as there is no json for it yet
  - pushd .
  - git clone https://github.com/espressif/arduino-esp32.git "${SKETCHBOOK_FOLDER}/hardware/espressif/esp32"
  - cd "${SKETCHBOOK_FOLDER}/hardware/espressif/esp32"
  - git submodule update --init --recursive
  - cd tools
  - python2 get.py
  - popd

  # install libraries needed
  - install_library "ArduinoJson"
  - install_library "https://github.com/bbx10/WebServer_tng.git"

  # install the library (WiFiManager) from repo
  - install_library

script:
  - build_sketch "${EXAMPLES_DIR}" "${ESP8266_DEVICE}" "false" "1.8.5"
  - build_sketch "${EXAMPLES_DIR}" "${ESP32_DEVICE}"   "false" "1.8.5"

notifications:
  email:
    on_success: change
    on_failure: change
